### ISSUE TITLE
Package OpenNI2.2

### ISSUE THREAD

**Issue by jspricke** [hcw70/OpenNI2#10]

**Comment by hcw70** [comment]
Just uploaded adapted patches for OpenNi2.3.0.x. Please check them if they are ok, Branch debian-develop. Please test them.

**Comment by jspricke** [comment]
Hi Hauke,

great to see you back working on Openni :). Three things:
- Could you do a debclean and remove the generated files from the repo?
- Did you test if this version is ABI compatible? Otherwise we should change the SONAME to .1. Try the abi-compliance-checker.
- Whats the status of getting this into Debian?

Cheers Jochen

**Comment by hcw70** [comment]
Hi Jochen.

Im working on getting sth into debian still. Got now a contact from Hans Steiner.

What generated files do you see?

I will check the ABI compliance

Regards

Hauke

**Comment by hcw70** [comment]
Ok, should now be ok. Anything else? Please re-test.

**Comment by hcw70** [comment]
Btw. How to get that git-dch to do something reasonable?

**Comment by jspricke** [comment]
Hi Hauke,

The ABI is part of the package name, so we should change them as well (see my pull request #16).
For git-dch, try the --auto flag, also if you use git-buildpackage --git-tag it should work.

**Comment by mikeferguson** [comment]
@jspricke Which repository/branch are you releasing 2.2 from these days? I need to submit a patch to the debian, that I'd like to get into ROS (it's pretty simple, just a udev rule update), but I don't know where to submit it.

**Comment by jspricke** [comment]
Hi Mike,

Great to hear you are looking into Openni, we are using thus one http://anonscm.debian.org/gitweb/?p=pkg-multimedia/openni2.git.

Cheers Jochen

**Comment by mikeferguson** [comment]
How does one submit a patch to that repository?

**Comment by hcw70** [comment]
btw, i have merged the latest changes from  http://anonscm.debian.org/gitweb/?p=pkg-multimedia/openni2.git.into this repo here.

**Comment by jspricke** [comment]
- Michael Ferguson notifications@github.com [2014-05-01 14:24]:
  > How does one submit a patch to that repository?

Easy way: send them to me and I will push them.
Normal way: fill a bug against the package and attach the patch (sadly
it's still not in Debian, so we can't do that right now @hcw70 what's
the status here?)
Optimal way: register on alioth.debian.org and ask for access to the
pkg-multimedia group.

Cheers Jochen

**Comment by hcw70** [comment]
@jspricke Status is that i was unable to get any access to debian repo. I recently merged those changes however back into mine....
